# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/node:20.2.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
     # Checkout the code from the branch into the working_directory
                - checkout
                # Log the current branch
                - run:
                    name: Show current branch
                    command: echo ${CIRCLE_BRANCH}
                # Install project dependencies
                - run:
                    name: Install local dependencies
                    command: npm install
                # Build Angular
                - run:
                    name: Install local dependencies
                    command: npm run build
                # Test the source code
                - run:
                    name: Creating Dummy Artifacts
                    command: |
                      mkdir /tmp/artifacts;
                      cp dist/portfolio-mathieu-almon > /tmp/artifacts;
                - store_artifacts:
                    path: /tmp/artifacts

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
